name: vscode-python-opt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - typer>=0.20,<0.21
    - cplex>=22.1.2,<22.1.3
    - docplex>=2.30,<2.31
    - gurobipy>=13.0,<13.1
    - highspy>=1.12,<1.13
    - mip>=1.15,<1.16
    - ortools>=9.14,<9.15
    - pychoco>=0.2.4,<0.2.5
    - PySCIPOpt>=5.6,<5.7
    - xpress>=9.8,<9.9
    # dev dependencies
    - basedpyright>=1.33.0
