name: vscode-python-opt
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - typer>=0.20
    - cplex>=22.1.2
    - docplex>=2.30
    - gurobipy>=13.0
    - highspy>=1.12
    - mip>=1.15
    - ortools>=9.14
    - pychoco>=0.2.4
    - PySCIPOpt>=5.6
    - xpress>=9.8
    # dev dependencies
    - basedpyright>=1.33.0
