[project]
name = "vscode-python-opt"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
    "cplex>=22.1.2,<22.1.3",
    "docplex>=2.30,<2.31",
    "gurobipy>=12.0,<12.1",
    "highspy>=1.11,<1.12",
    "mip>=1.15,<1.16",
    "ortools>=9.14,<9.15",
    "pychoco>=0.2.3,<0.2.4",
    "pyscipopt>=5.6,<5.7",
    "typer>=0.20,<0.21",
    "xpress>=9.7,<9.8",
]
description = "Simple examples of running discrete optimization solvers in Python"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E.*"]

[dependency-groups]
dev = [
    "basedpyright>=1.31.6",
]
