[project]
name = "vscode-python-opt"
version = "0.1.0"
requires-python = ">= 3.11"
dependencies = [
    "cplex>=22.1.2",
    "docplex>=2.30",
    "gurobipy>=13.0",
    "highspy>=1.12",
    "mip>=1.15",
    "ortools>=9.14",
    "pychoco>=0.2.4",
    "pyscipopt>=5.6",
    "typer>=0.20",
    "xpress>=9.8",
]
description = "Simple examples of running discrete optimization solvers in Python"
readme = "README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E.*"]

[dependency-groups]
dev = [
    "basedpyright>=1.33.0",
]
